<?php
$block = $this->getBlock();
$isBoleto = $block->isBoleto();
$isCc = $block->isCc();
?>
<div class="checkout-success-additional">
	<dl>
		<dd><?php echo __('Transaction State'); ?></dd>
		<dt class="status"><?php echo __('Transaction.State.' . $block->getPayuTransactionState()); ?></dt>

		<dd><?php echo __('PayU Order ID'); ?></dd>
		<dt><?php echo $block->getOrderId(); ?></dt>

		<dd><?php echo __('PayU Transaction ID'); ?></dd>
		<dt><?php echo $block->getTransactionId(); ?></dt>

		<?php if($isBoleto):?>
			<dd><?php echo __('Bar Code'); ?></dd>
			<dt class="barcode"><?php echo $block->getBoletoBarcode(); ?></dt>

			<dd><?php echo __('Boleto Link'); ?></dd>
			<dt class="link">
				<a href="<?php echo $block->escapeUrl($block->getBoletoLink()); ?>">
					<?php echo $block->escapeHtml(__('Click here to open the Boleto')); ?>
				</a>
			</dt>

			<dd><?php echo __('Boleto PDF'); ?></dd>
			<dt class="pdf">
				<a href="<?php echo $block->escapeUrl($block->getBoletoPdfLink()); ?>">
					<?php echo $block->escapeHtml(__('Click here to download the Boleto PDF')); ?>
				</a>
			</dt>
		<?php elseif ($isCc):?>
			<dd><?php echo __('Credit Card Type'); ?></dd>
			<dt><?php echo $block->getCcType(); ?></dt>

			<dd><?php echo __('Last Credit Card Number'); ?></dd>
			<dt><?php echo sprintf('xxxx xxxx xxxx %s', $block->getCcLast4()); ?></dt>

		  <?php if($block->hasInstallments()):?>
				<dd><?php echo __('Installments'); ?></dd>
				<dt><?php echo $block->getFormattedInstallmentAmount(); ?></dt>
			<?php endif;?>
		<?php endif;?>
	</dl>
</div>